recipegram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from recipes import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name = "index"),
    path('about/',views.about, name = "about"),
    path('recipes/',include("recipes.urls")),
    path('user/',include("user.urls")),
    
    #recipes/create
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
#new

from django.contrib import admin
from django.urls import path
from . import views

app_name = "recipes"


urlpatterns = [
    path('dashboard/', views.dashboard, name = "dashboard"),
    path('addrecipe/',views.addRecipe, name = "addrecipe"),
    path('recipe/<int:id>',views.detail, name = "detail"),  
    path('update/<int:id>',views.updateRecipe, name = "update"),  
    path('delete/<int:id>',views.deleteRecipe, name = "delete"),  
    path('',views.recipes, name = "recipes"),  
    path('comment/<int:id>',views.addComment, name = "comment"),  
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"


urlpatterns = [
    #user/register
    path('register/', views.register, name = "register"),
    #user/login
    path('login/', views.loginUser, name = "login"),
    #user/logout
    path('logout/', views.logoutUser, name = "logout"),
]

recipes/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Recipe(models.Model):
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE)
    title = models.CharField(max_length = 50)   
    content = RichTextField()       
    created_date = models.DateTimeField(auto_now_add=True)
    recipe_image = models.FileField(blank = True , null = True , verbose_name = "Please,Add an image...")
    def __str__(self):  
        return self.title

class Comment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,verbose_name = "Recipe",related_name="comments")
    comment_author = models.CharField(max_length = 50, verbose_name = "name")
    comment_content = models.CharField(max_length = 200, verbose_name = "comment")
    comment_date = models.DateTimeField(auto_now_add=True)

def __str__(self):
    return self.comment_content



    

user/models.py
from django.db import models

# Create your models here.

recipes/forms.py
from django import forms
from .models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["title","content","recipe_image"]
        

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "Username")
    password = forms.CharField(label = "Password",widget = forms.PasswordInput)




class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50 , label = "Username")
    password = forms.CharField(max_length=20 , label = "Password", widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20 , label = "Confirm Password", widget = forms.PasswordInput)
    

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Passwords no validated")

        values = {
            "username" : username,
            "password" : password
        }
        return values

recipes/views.py
from django.shortcuts import HttpResponse, redirect, render,get_object_or_404,reverse
from .forms import RecipeForm
from .models import Recipe,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
def recipes(request):
    keyword = request.GET.get("keyword")

    if keyword:
        recipes = Recipe.objects.filter(title__contains = keyword)
        return render(request,"recipes.html",{"recipes":recipes}) 
    
    recipes = Recipe.objects.all()

    return render(request,"recipes.html",{"recipes":recipes})



def index(request):
    context = {
        "numbers":[1,2,3,4,5,6]
    }
    return render(request,"index.html",context)     


def about(request):
    return render(request,"about.html")

@login_required(login_url="user:login")
def dashboard(request):
    recipes = Recipe.objects.filter(author = request.user)

    context = {
        "recipes":recipes
    }

    return render(request,"dashboard.html",context) 

@login_required(login_url="user:login")
def addRecipe(request):
    form = RecipeForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        recipe = form.save(commit=False)
        
        recipe.author = request.user
        recipe.save()

        messages.success(request,"It is created successfully")
        return redirect("recipes:dashboard")

    return render(request,"addrecipe.html",{"form":form})


def detail(request,id):
    # recipe = Recipe.objects.filter(id = id).first()
    recipe = get_object_or_404(Recipe, id = id)

    comments =recipe.comments.all()


    return render(request,"detail.html",{"recipe":recipe,"comments":comments})

@login_required(login_url="user:login")
def updateRecipe(request,id):
    recipe = get_object_or_404(Recipe, id = id)
    form  = RecipeForm(request.POST or None,request.FILES or None,instance=recipe)
    if form.is_valid():
        recipe = form.save(commit=False) 
        
        recipe.author = request.user
        recipe.save()
        
        messages.success(request,"It is updated successfully")
        return redirect("recipes:dashboard")
    return render(request,"update.html",{"form":form})


@login_required(login_url="user:login")
def deleteRecipe(request,id):
    recipe = get_object_or_404(Recipe, id = id)
    recipe.delete()

    messages.success(request,"It is deleted successfully")
    

    return redirect("recipes:dashboard")


def addComment(request,id):

    recipe = Recipe.objects.get(pk=id)

    
    if request.POST:
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(recipe = recipe, comment_author = comment_author, comment_content = comment_content)

        newComment.save() 

    return redirect(reverse("recipes:detail",kwargs={"id":id}))

    

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout



# Create your views here.

def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        newUser = User(username = username)
        newUser.set_password(password)

        newUser.save()
        #for automatically login after registeration  
        login(request,newUser)
        messages.info(request,"You registered successfully")
        return redirect("index")
                 
    context = {
        "form" : form
    }
    return render(request,"register.html",context)

    #     if form.is_valid():
    #         username = form.cleaned_data.get("username")
    #         password = form.cleaned_data.get("password")
    #         newUser = User(username = username)
    #         newUser.set_password(password)

    #         newUser.save()
    #         #for automatically login after registeration  
    #         login(request,newUser)
            
    #         return redirect("index")


            
    # else:
    #     form = RegisterForm()

    #     context = {
    #         "form" : form
    #     }
    #     return render(request,"register.html",context)
    


def loginUser(request):
    form = LoginForm(request.POST or None)
    context = {
        "form" : form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username, password = password)

        if user is None:
            messages.info(request,"Username or password is not found")
            return render(request,"login.html",context)
        
        messages.success(request,"You login successfully")
        login(request,user)

        return redirect("index")

    return render(request,"login.html",context)

def logoutUser(request):
    logout(request)
    messages.success(request,"You log out successfully")
    return redirect("index")
    
 
  
   
    
     
      
       
        
         
          

templates/about.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
    
    <link rel="stylesheet" href="{% static 'css/addrecipe.css' %}">

    <div class="row" id="div_dashboard"> 
        <div class="col-md-10 offset-md-1">

            <h3 style="color: azure;">About</h3>
            <hr>
            <p style="color: azure;">Hello,Everyone!!
                This blog is created in 2019. We are here for you and your mouth-pleasing
                Appetizing, inspiring, mouth-watering ... Not only recipes ... Feeding while laughing ...

            Yemek.com, to learn the Italian cuisine to make her lover happy, to leave the power to produce wine in the south, the most dreamed to open rice pilgrim in Cihangir, the only culinary skill menemen can boast, according to the location of the hotel to eat according to the hotel also, a giant souffle eaten that day to feel the need to pay attention to the food during the whole week, the taste of the food without tasting salt, Instagram'a to take photos of the site to afford to cool the food.

            Not only for those who want to feed themselves, but for those who pursue a pleasure.

            With its ambitious team of different tastes and colors and many friendly and partners who contribute from outside, Yemek.com has set up a huge, long, colorful table and has a lot of chairs.

            You have a chair at this delicious table. Whether as a writer or as a reader.

            Good thing you came, come again.

            Yours from us,






        </div>
      
     

    </div>

{% endblock body %} 

templates/addrecipe.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
 
{% load crispy_forms_tags %}

    <link rel="stylesheet" href="{% static 'css/addrecipe.css' %}">

    <div class="row" id="div_dashboard">

        <div class="col-md-10 offset-md-1">
            <h3>Create Recipe</h3>
            <hr>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                {{form | crispy}}
                <br>
                <button type="submit" class = "btn btn-danger">Add Recipe</button>
            </form>
        </div>
  
    </div>

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <body>    
        <h3 style="color: azure;">Profile</h3>

        <div class="profile-card">
            <div class="image-container">
                <img src="/static/css/images/gordan.jpeg" id="image_div" style="width: 100%;">
                <div class="title">
                    <h2>Jone Doe</h2>
                </div>
            </div>
        </div>
    </body>

    
    <hr>
    <p style="color: azure;">
        Welcome, <small>{{request.user.username}}</small>
    </p>

    <hr>

    <a class="btn btn-danger" href="/recipes/addrecipe">Add Recipe</a>
    <hr>
    {% if recipes  %}
        <table class="table table-dark">
            <thead>
                <tr>
                <th scope="col">id</th>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Date</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for recipe in recipes %}
                    <tr>
                    <th scope="row">{{recipe.id}}</th>
                    <td><a href="/recipes/recipe/{{recipe.id}}">{{recipe.title}}</a></td>
                    <td>{{recipe.author.username}}</td>
                    <td>{{recipe.created_date}}</td>
                    <td><a href="/recipes/update/{{recipe.id}}" class = "btn btn-danger">Edit</a></td>
                    <td><a href="/recipes/delete/{{recipe.id}}" class = "btn btn-danger">Delete</a></td>
                    </tr>

                {% endfor %}

            </tbody>
        </table>
    {% else %}
        <div class="alert alert-danger">
            You have no recipe for now.
        </div>
    {% endif %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
 <link rel="stylesheet" href="{% static 'css/details.css' %}">
    <div class="row" id="div_dashboard">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h3 class="mt-4">{{recipe.title}}</h3>

        <!-- Author -->
        <p class="lead">
          by
            {{recipe.author.username}}
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{recipe.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if recipe.recipe_image %}
          <img class="img-fluid rounded" src="{{recipe.recipe_image.url}}" alt="">
        {% else %}
        {% endif %}
        
            

        <hr>

        <!-- Post Content -->
        <p class="lead">
        
            {{recipe.content|safe}}
        
        
        
        </p>
        
        <hr>  
        <h4>Comments</h4>
        <hr>
        {% if comments %}
          {% for comment in comments %}
           <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{comment.comment_author}}</h5>
              {{comment.comment_date}} <br>
              {{comment.comment_content}}
            </div>
          </div>
          {% endfor %}
         
        {% else %}
        <div class="alert alert-danger">
          There is no comment here.You can do it:)
        </div>
        {% endif %}


 <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form method = "post" action="{% url 'recipes:comment' recipe.id %}">
            {% csrf_token %}
              <div class="form-group">
                  <label for="formGroupExampleInput">Name</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="Please,Enter name">
                </div>
              <div class="form-group">
                  <label for="formGroupExampleInput">Comment</label>
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
          </div>

        </div>



{% endblock body %}

templates/includes/navbar.html
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="/">Recipegram</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
            <a class="nav-link" href="/recipes">Recipes
              <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://www.instagram.com/yemekcom/">Instagram</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About</a>
            </li>
          </ul>

          
          <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
              <li class="nav-item active">
                <a class="nav-link" href="/recipes/dashboard">Profile</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="/user/logout">Logout</a>
              </li>
            {% else %}
              <li class="nav-item active">
                <a class="nav-link" href="/user/login">Login</a>
              </li>

            {% endif %}

              <li class="nav-item active">
                <a class="nav-link" href="/user/register">Register</a>
              </li>
          </ul>
         
        </div>
      </nav>

templates/includes/posttemplate.html
<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Post Title</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">Start Bootstrap</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on January 1, 2019 at 12:00 PM</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

        <blockquote class="blockquote">
          <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <footer class="blockquote-footer">Someone famous in
            <cite title="Source Title">Source Title</cite>
          </footer>
        </blockquote>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <!-- Comment with nested comments -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>






    {% comment %} <div class="jumbotron text-center" style="background-image: url('/../static/css/plate.jpg');">
        <h3 style="color: rgb(235, 233, 236);">Welcome to Recipegram</h3>
        <p style="color: rgb(235, 233, 236);">This blog is for all people that like cooking</p>
    </div> {% endcomment %}




{% comment %} 
    {% for number in numbers %}
        <li>{{number}}</li>
    {% endfor %} {% endcomment %}

templates/index.html
{% extends "layout.html" %}
{% load static %}

{% block body %}    

  <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>Recipegram</title>




    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,500,500i,700,800i">
    <link rel="stylesheet" type="text/css" href="{% static 'static/index.css' %}"/>


        <div class="container" id="mainindex.css">
      <div class="jumbotron text-center" style="background:rgba(0, 0, 0, 0.3);">
        <div class="opentext">
          <h1 class="font-italic" style="color: white;">Bon Appétit</h1>
          <br>
          <h3 class="font-italic" style="color: white;">Join us and enjoy new recipes</h3>
          <br>
        
        </div>
      </div>
    </div>    

   <body>
   
    
   </body>
   
{% endblock body %}

templates/layout.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Layout</title>
</head>
<body>
    {% include "includes/navbar.html" %}
 
    {% if messages %}

        {% for message in messages %}
        {% if message.tags == "info" %}
            <div class="alert alert-danger">{{ message }}</div>
        {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}

    
        {% endfor %}

    {% endif %}
   
    <div style="margin-top : 100px; margin-bottom:100px;" class="container"> 

        {% block body %}

        {% endblock body %}


    </div>






    
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

     
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% load static %}
{% block body %}    
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <body>
        
    </body>
{% load crispy_forms_tags %}
    <div class="row" id="loginform">
        <div class="col-md-3 offset-md-3">
            <h3>Login</h3>
            <hr>
              <form method="post" id="form">
        {% csrf_token %}
        {{ form | crispy }}
        <br>
        <button type="submit" class = "btn btn-danger">Login</button>
    </form>
        </div>
  
    </div>

  

{% endblock body %} 

templates/register.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
        <body>
  
        </body>
{% load crispy_forms_tags %}

<div class="row" id="registerform">
        <div class="col-md-3 offset-md-3">
                <h3>Register</h3>
                <hr>
              <form method="post" id="form">
        {% csrf_token %}
        {{ form | crispy }}
        <br>
        <button type="submit" class = "btn btn-danger">Register</button>
    </form>
        </div>
  
</div>


{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
 
{% load crispy_forms_tags %}
 <link rel="stylesheet" href="{% static 'css/update.css' %}">
    <div class="row" id="div_dashboard">
        {% comment %} <div class="col-md-3 offset-md-3"> {% endcomment %}
        <div class="container">
            <h3>Update Recipe</h3>
            <hr>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                {{form | crispy}}
                <br>
                <button type="submit" class = "btn btn-danger">Update Recipe</button>
            </form>
        </div>
  
    </div>

{% endblock body %}